language: objective-c
osx_image: xcode8.3

branches:
  only:
    - master

env:
  matrix:
    - TEST_TYPE=iOS

-before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
script:
- |
    xcodebuild clean test  -scheme AlamofireURLCacheDemo -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' -enableCodeCoverage YES | xcpretty
after_success:
    - sleep 5
      bash <(curl -s https://codecov.io/bash)
